// <auto-generated />
using System;
using API_CRUD.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API_CRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API_CRUD.Models.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 2, 1, 17, 50, 47, 640, DateTimeKind.Local).AddTicks(223),
                            Password = "123",
                            Status = 1,
                            UserName = "Emre"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 2, 1, 17, 50, 47, 640, DateTimeKind.Local).AddTicks(2929),
                            Password = "123",
                            Status = 1,
                            UserName = "Erkan"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 2, 1, 17, 50, 47, 640, DateTimeKind.Local).AddTicks(2956),
                            Password = "123",
                            Status = 1,
                            UserName = "Erol"
                        });
                });

            modelBuilder.Entity("API_CRUD.Models.Concrete.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeleteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2022, 2, 1, 17, 50, 47, 570, DateTimeKind.Local).AddTicks(9318),
                            Description = "Size yakışan tüm ürünler.",
                            Name = "Giyim",
                            Slug = "giyim",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2022, 2, 1, 17, 50, 47, 634, DateTimeKind.Local).AddTicks(9189),
                            Description = "Hem şık, hem ucuz.",
                            Name = "Aksesuar",
                            Slug = "aksesuar",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2022, 2, 1, 17, 50, 47, 634, DateTimeKind.Local).AddTicks(9266),
                            Description = "Hem konforlu, hem şık, hem ucuz.",
                            Name = "Ayakkabı",
                            Slug = "ayakkabı",
                            Status = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
